version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
