version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-db:
    driver: local
