version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - easy-order

  app-api:
    build: .
    container_name: app-api
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - easy-order
    depends_on:
      - postgres-db

networks:
  easy-order:
    driver: bridge

volumes:
  postgres-db:
